<?php /* Template Name: home */ ?>

<?php get_header(); ?>

	<!-- content -->
	<div id="primary" class="content-area">
	
		<div class="left">
		
			<!-- caixa de pesquisa -->
			<input type="text" name="search" placeholder="Pesquisar" class="pesquisa" id="inputSearch">
			
			<!-- botao pesquisa -->
			<div class="pesquisa" id="botaoPesquisaHomepage">
				<img src="<?php echo get_bloginfo('template_directory'); ?>/images/buttons/searchButton.gif"/>
			</div>
		
		</div>
		<!-- Wrapper content Quadrados Homepage -->
		<div class="wrapperQuadrados">
		
			<div class="left">
				<!-- first big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				
				

				
			</div>
			
			<div class="right">
				<!-- second big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
			</div>
			
			<!-- -->
			<!-- REPETE O LEFT E RIGHT! SEGUNDA METADE -->
			<!-- -->
			
			<div class="left">
				<!-- third big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				
			</div>
			
			<div class="right">
				<!-- fourth big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
			</div>
		</div>
	</div><!-- #primary -->
	
<?php get_footer(); ?>
