<?php
/**
 * The main template file.
 *
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file exists.
 * Learn more: http://codex.wordpress.org/Template_Hierarchy
 *
 * @package dromedare
 */

get_header(); ?>

	<!-- content -->
	<div id="primary" class="content-area">
		
		<!-- pesquisa (não tem a caixa funcionando) -->
		<div class="pesquisa" id="caixaPesquisaHomepage">
			
			<!-- botao pesquisa -->
			<div class="pesquisa" id="botaoPesquisaHomepage">
				<img src="<?php echo get_bloginfo('template_directory'); ?>/images/buttons/searchButton.gif"/>
			</div>
		</div>
		
		<!-- Wrapper content Quadrados Homepage -->
		<div class="wrapperQuadrados">
		
			<div class="left">
				<!-- first big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				
				

				
			</div>
			
			<div class="right">
				<!-- second big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
			</div>
			
			<!-- -->
			<!-- REPETE O LEFT E RIGHT! SEGUNDA METADE -->
			<!-- -->
			
			<div class="left">
				<!-- third big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				
			</div>
			
			<div class="right">
				<!-- fourth big square -->
				<div class="squares" id="big"><img src="<?php echo get_bloginfo('template_directory'); ?>/images/squares/bigSquareEmpty.gif"/></div>
				
				<!-- 16 small squares -->
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
				<div class="squares" id="small"><img src="<?php echo get_bloginfo('template_directory') ?>/images/squares/smallSquareEmpty.gif"/> <h2><span class="tituloDesafio">Título</span></h2><img src="<?php echo get_bloginfo('template_directory'); ?>/images/tags/none.gif" class="tags"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/difficulty/none.gif" class="difficulty"/><img src="<?php echo get_bloginfo('template_directory'); ?>/images/countries/none.gif" class="flag"/></div>
			</div>
		</div>
	</div><!-- #primary -->
	
<?php get_footer(); ?>
